language: python

python:
    - 2.7
    - pypy
    - 3.3
    - 3.4
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-de
install: pip install tox
script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')

matrix:
    allow_failures:
        - python: 3.3
        - python: 3.4
